def build_email_html(intelligence: dict) -> str:
    html = f"""
    <html>
    <body style="font-family:Arial, sans-serif; line-height:1.6;">

    <h2>🧠 Daily AI Intelligence Brief</h2>
    <p><b>Date:</b> {intelligence['date']}</p>

    <p>
    For deeper insights, trend analysis, and source links,
    please refer to the attached <b>AI Intelligence Report (PDF)</b>.
    </p>

    <h3>Executive Summary</h3>
    <p>{intelligence['executive_summary']}</p>

    <h3>Trend Snapshot</h3>
    <ul>
    """

    for section in intelligence["sections"]:
        html += f"<li><b>{section['title']}</b> — Impact Score: {section['impact_score']}/10</li>"

    html += "</ul>"
    html += "<h3>Key Developments</h3>"

    for section in intelligence["sections"]:
        html += f"<h4>{section['title']}</h4>"

        for item in section["items"]:
            html += f"""
            <p>
                <b>{item['headline']}</b><br><br>
                {item['summary']}<br><br>
                <a href="{item['url']}">Read more</a>
            </p>
            <hr>
            """

    html += """
    <p><b>📎 Attached:</b> Full AI Intelligence PDF Report</p>
    <p style="font-size:12px;color:#555;">
        Generated by AI-Powered Intelligence Digest System
    </p>

    </body>
    </html>
    """

    return html
